### ISSUE TITLE
Change XP Bar Size

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#10]
Is it possible to add an option to change the size of the XP bar?

This is useful to slow down player evolution;

Thank you.

![image](https://user-images.githubusercontent.com/4999783/132412400-39d98714-4da6-421f-87ce-d137e97358fc.png)

**Comment by drewg13** [comment]
Done in the last release.  You should be able to modify via macros.

**Comment by drewg13** [comment]
Example code:
`let actor = canvas.tokens.controlled[0].actor;
let newMax = actor.data.data.attributes.insight.expMax + 1;
let updated = await Actor.updateDocuments([{_id: actor.id, "data.attributes.insight.expMax": newMax}]);
console.log(updated);`
