### ISSUE TITLE
Spam Items Description to the Chat

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#11]
Hi

It's very common in other system to let the players spam the item text to the chat to quickly share. It's useful for the GM and the players.

Can you make that possible?

Thank you.

![image](https://user-images.githubusercontent.com/4999783/132415115-21bb2716-4b8a-4182-8574-db54c56f883d.png)

![image](https://user-images.githubusercontent.com/4999783/132415136-f5cc74fe-466b-4af1-9f95-1b6db46b995a.png)

**Comment by drewg13** [comment]
I'll look into this one, I don't immediately know how to approach it.  But plenty of other systems do it, so it shouldn't be that hard.

**Comment by drewg13** [comment]
Done!  That was easier than I thought and I really like how it works.  I adapted code from the brilliant Forbidden Lands system.  Let me know what you think and if I missed anything.

**Comment by brunocalado** [comment]
How can I spam to chat? I can't do it.

**Comment by brunocalado** [comment]
Worked

**Comment by brunocalado** [comment]
Thank you
