### ISSUE TITLE
Missing Translation Tags

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#12]
Hi. Sorry bother you again. But, I think there is more missing tags for translation.

Is it possible to translate Fortune Roll and Roll?

![image](https://user-images.githubusercontent.com/4999783/132419078-a8911b40-ba27-415f-90fd-a14eb26c2bf6.png)

Thank you.

**Comment by drewg13** [comment]
This will be in the next release, thanks for finding these!  I'm still not sure why Cancel worked and Roll did not, they were set up the same way...

**Comment by brunocalado** [comment]
Thank you.

I couldn't find
![image](https://user-images.githubusercontent.com/4999783/132607568-58b70024-26dc-4b29-9526-f92e9f648198.png)

**Comment by drewg13** [comment]
Darnit, missed that one.  One more release coming...
