### ISSUE TITLE
Add Macro to System Compendium

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#14]
Add Macro to System Compendium

Macro GUI for XP Bar
![image](https://user-images.githubusercontent.com/4999783/132957970-d636767f-07a3-42d3-844d-2ac4753002c1.png)

Macro
https://raw.githubusercontent.com/brunocalado/mestre-digital/master/Foundry%20VTT/Macros/Sistemas%20Diversos/BladesintheDark-XpBar.js

**Comment by drewg13** [comment]
Would it be easier/make more sense if I include a bunch of these sorts of things as system settings instead?  That way you could set the default values for all new actors once.  But I suppose you'd still need a macro like this for existing actors and on the fly changes.

**Comment by drewg13** [comment]
I think the macro is still useful for modifying existing actors, but I made some modifications.  Let me know what you think of the settings and if any other variable could be useful as settings.  Fixed in 1.10.1.
