### ISSUE TITLE
Missing Translation Tags

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#15]
Hi.

I can't find where to translate:
![image](https://user-images.githubusercontent.com/4999783/133109708-ae1bd633-077a-4c96-a34e-77bf787e59a0.png)

Thank you.

**Comment by drewg13** [comment]
Yep, more hardcoded strings. These will be an easy fix.

**Comment by drewg13** [comment]
Fixed in 1.10.1.
