### ISSUE TITLE
Entanglements Roll

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#17]
Hi!

Can you make the button Wanted roll for Entanglements?

![image](https://user-images.githubusercontent.com/4999783/133467948-4bb067a9-fc40-4031-ab24-7b2a5f57fb51.png)

I was writing a macro like the one for BID, but it'll be easier to roll from the universe.

bid macro: source: https://raw.githubusercontent.com/brunocalado/mestre-digital/master/Foundry%20VTT/Macros/Forged%20in%20the%20Dark/bid-entanglement.js
![image](https://user-images.githubusercontent.com/4999783/133468404-2a9efa8f-f828-4510-8e2e-6c65c43a5136.png)

**Comment by drewg13** [comment]
Excellent idea, added in 1.11.0
