### ISSUE TITLE
[Suggestion] Add Generators to Compedium

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#20]
What do you think about add these:

https://user-images.githubusercontent.com/4999783/133704482-19745ad0-31e9-474d-aa54-d329c21447c8.mp4

[Downloads.zip](https://github.com/drewg13/foundryvtt-scum-and-villainy/files/7181630/Downloads.zip)

**Comment by drewg13** [comment]
Also fun!  I'll play with these as well.

**Comment by drewg13** [comment]
Oof, I didn't realize that these are just iframes to web content.  They're useful and I might use them in my own games, but I don't think I want to include them in the system.  Thanks for introducing the concept though.
