### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#22]
Everytime I push update system this message appears:

![image](https://user-images.githubusercontent.com/4999783/134346663-a51e6055-d19b-4a37-8b02-bef36fc2b40d.png)

Can you fix it?

Thank you.

**Comment by drewg13** [comment]
That's weird, there were some issues with the FoundryVTT package admin system the other day when I was trying to release the last update.  Try updating now and if that doesn't bring you to 1.12.0, uninstall and re-install.
