### ISSUE TITLE
Weird update warning

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#24]
I tried to install it again.

I delete it from the folder. 

But, It still warning about an update.

The world shows:
![image](https://user-images.githubusercontent.com/4999783/134598046-f98ac0b1-c8cf-4221-b08e-b815e01a7ea9.png)

The system:
![image](https://user-images.githubusercontent.com/4999783/134598084-de14b3f5-fcbc-4619-b9f1-814a7e8ffbd0.png)

**Comment by drewg13** [comment]
Yep, I see it now, I botched the release and the old zip was tagged with the new release.  It should be fixed now, sorry about that.
