### ISSUE TITLE
standard for ship´AE

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#25]
I wrote a macro to track the AE and translate them. But, It could be more reliable if you make a standard **class** or **type**. 

![image](https://user-images.githubusercontent.com/4999783/134691364-9247e549-9cc0-4a67-a453-b8e33f6eead7.png)

Thank you

**Comment by drewg13** [comment]
I see what you mean now, it took me a while to even figure it out because they looked the same to me.  Should be fixed in 1.12.1.
