### ISSUE TITLE
Small Translation Issue

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#30]
Hi!

Can you help me fixing this for the translation? I just want to decrease the font size. I think I need to add some css to the translation module.

![image](https://user-images.githubusercontent.com/4999783/135672945-2918a931-a08c-4691-9ce5-fd54e7c0db06.png)

**Comment by drewg13** [comment]
I don't have the faintest idea how you'd go about overriding a CSS rule using a module, but the CSS rule governing the font size on those labels is:
```
* .big-teeth-section #trauma-list label {
  font-size: 19px;
}
```

Seems like an unusual effort for a minor visual detail to me though.  You could just make the sheet wider, the labels should flow properly.

**Comment by brunocalado** [comment]
worked. tks
