### ISSUE TITLE
Faction Clock and Objectives Visible at Universe Sheet

### ISSUE THREAD

**Issue by jacksands** [drewg13/foundryvtt-scum-and-villainy#32]
Would be possible to add the faction objective clock to the universe sheet, with a clickable icon to show what is the objective?

That would have the effect to know at a quick glance how is the situation of all factions, perhaps throw some pressure at the players, especially if the "Note  icon" only works if clicked by the GM.

to open every faction sheet to remember and adjust that is kind of a bummer, especially with many active factions...

Image add with the general concept 

In any way thanks for the system, having a great time with it!

![1](https://user-images.githubusercontent.com/7229143/136705666-36a1201f-a2cc-4fbd-bd20-a15aae3456b6.jpg)

**Comment by brunocalado** [comment]
This is a good idea.

**Comment by brunocalado** [comment]
Can you fix this?

![image](https://user-images.githubusercontent.com/4999783/137051828-9660355a-8c34-4c63-83c4-3ba6a24e3709.png)

I think you could turn the objetive into a tooltip for the clock.

**Comment by drewg13** [comment]
Ouch, that's probably because "Trabalhos" is considerably longer than "Jobs" and because I'm bad at CSS.  I like the tooltip idea though.

**Comment by drewg13** [comment]
Should be improved in 1.13.1

**Comment by jacksands** [comment]
Thank you, it is perfect!
