### ISSUE TITLE
[Suggestion] SCI FI UI

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#33]
Hi,

Any chance of port this UI to SV?

https://github.com/coboye/sfrpg-modern-ui

**Comment by drewg13** [comment]
Heavy CSS work like that is way way outside my comfort zone. Personally, I use the Ernie's Modern UI module with the accent color changed from orange to#33b5e5. I'll look into it, but I'd say it's unlikely.

**Comment by drewg13** [comment]
You seem to have some coding skill yourself, feel free to submit a merge request if you want to tackle it.

**Comment by brunocalado** [comment]
I like Ernie's Modern UI. I'm using Minimal at the moment.

I may try it. But, CSS is something I don't really can do much.
