### ISSUE TITLE
[Suggestion] Replace Icon for Animated Webp

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#34]
Hi.

What do you think about replace the planet icon by animated webp? 

There is a free to use generator. I can share mine.

https://user-images.githubusercontent.com/4999783/138615995-03c5266c-9f3a-48d4-8374-8e74522c5f62.mp4

**Comment by drewg13** [comment]
So I've been playing with this to make the system support it.  There are some inherent system limitations that no amount of programming can overcome, so the setup process to make it work is a bit cumbersome.

You have to:
 - generate the animated GIF using the PixelPlanets program or something similar
 - convert the GIF into **both** a WEBP (for the item icon) and a WEBM (for the tile)
 - give them both an identical root filename, for example, image.webp and image.webm
 - put them both in the same filesystem location
 - assign the WEBP file as the item's icon
 - drag the item onto the scene

Let me know what you think.

https://user-images.githubusercontent.com/1455026/146687028-1e1931b6-a53f-4f4a-afa1-0aaefa8b6025.mp4

**Comment by brunocalado** [comment]
There are softwares that convert a entire folder. Gif to webm and webp.

I'm already doing this. I can't share my updated pack. I just have to update the webp pack.
https://user-images.githubusercontent.com/4999783/146695190-7c8bae39-c17a-431b-b0df-4721d7753a39.mp4

**Comment by brunocalado** [comment]
[webp-share.zip](https://github.com/drewg13/foundryvtt-scum-and-villainy/files/7741811/webp-share.zip)

**Comment by brunocalado** [comment]
[webm-share-3.zip](https://github.com/drewg13/foundryvtt-scum-and-villainy/files/7741825/webm-share-3.zip)
[webm-share-4.zip](https://github.com/drewg13/foundryvtt-scum-and-villainy/files/7741826/webm-share-4.zip)
[webm-share-5.zip](https://github.com/drewg13/foundryvtt-scum-and-villainy/files/7741827/webm-share-5.zip)
[webm-share-1.zip](https://github.com/drewg13/foundryvtt-scum-and-villainy/files/7741828/webm-share-1.zip)
[webm-share-2.zip](https://github.com/drewg13/foundryvtt-scum-and-villainy/files/7741829/webm-share-2.zip)

**Comment by brunocalado** [comment]
Do you want the process to mass convert?

**Comment by brunocalado** [comment]
I think you could add this as a scene in a pack: https://i.redd.it/9yf4h31s3ur21.png

**Comment by brunocalado** [comment]
If you want to portal, you can use JB2A. It's legal to use under CC.

**Comment by drewg13** [comment]
Right, I'm just trying to make it slightly easier to set up.  There's a pretty significant bug related to WEBM tiles in v9, so I may hold off release until that's resolved.  It works really well otherwise though.
I'll take a look at the ones you already have, I've already done quite a few the manual way.  I can't include the Procyon map, as one of the conditions for permission to make the system was that I don't use any of the art.

**Comment by drewg13** [comment]
I might use yours for the random assignments for homebrew planets and stars, if you don't mind.

**Comment by brunocalado** [comment]
> of the conditions for permission to make the system was that I don't use any o

cool

**Comment by drewg13** [comment]
V9 Stable fixed the bug, so it should be good to go in the next release.
