### ISSUE TITLE
Rework Starting Ability Feature

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#40]
Hi. Very cool new feature.

I want to make a suggestion.
- Remove special chars from the name and make this a checkbox in the item.
- Read the checkbox and add a marker to the text instead of indicate what it is.
- Xeno is also a starting ability if you want to replace. 

![image](https://user-images.githubusercontent.com/4999783/145688198-1f75d5b1-4f53-4d8c-b898-c0c9a39fcf46.png)

Savage Worlds did this and broke lots of stuff (macros, translations). They rolled back and used the solution above. Symbol detection on items titles are not reliable.

Thank you for everything.

**Comment by drewg13** [comment]
Good idea, harder to implement though.  I'll see how to go about it.

**Comment by drewg13** [comment]
I really like the way this turned out, great suggestion!
