### ISSUE TITLE
Translation Tags

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#42]
Hi.

Can you add translation tags for:
![image](https://user-images.githubusercontent.com/4999783/145720486-1dd5350c-5888-41a3-a1ec-ab6f8770d98e.png)

Tks

**Comment by drewg13** [comment]
They're both already in there.
The header is from here:
![image](https://user-images.githubusercontent.com/1455026/145721834-24c71b8c-d5d8-4e83-8ce5-a6fe1384c130.png)
The legend is a new key here:
![image](https://user-images.githubusercontent.com/1455026/145721855-daa32f64-9c7b-4e09-841d-61f4816fe66a.png)
