### ISSUE TITLE
Can't Translate Vice

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#44]
Hi. I can't translate vice in the system.
![image](https://user-images.githubusercontent.com/4999783/146285063-3299a922-1cc2-4f9c-81d3-fd7ab82cf336.png)

```
  "BITD.vice": "Vício",
  "BITD.Vice": "Vício",
```

Thank you

**Comment by drewg13** [comment]
Got it, that was a tricky one.  This will be in the next release.  Good find.
