### ISSUE TITLE
Version Update

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#48]
Hi.

v9 let you use `  "compatibleCoreVersion": "9",` what prevents the anoying warning. Wouldn't be good to use it?

![image](https://user-images.githubusercontent.com/4999783/147396719-459e82af-b097-4e6c-b02f-5b8783e49f7d.png)

**Comment by drewg13** [comment]
Well aware of this, but there were numerous breaking changes in earlier versions of V9, so I was testing each release as it came out.  I'll try to remember to do this in my next release though.
