### ISSUE TITLE
I can't add a friend with the button in the actor sheet

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#5]
Great job with this system! Thank you.

I can't add a friend with the button in the actor sheet

![image](https://user-images.githubusercontent.com/4999783/129457631-a71622ad-9b20-4079-a8b9-635fc66e4736.png)

**Comment by drewg13** [comment]
Does that character have a Class added?  I can't see the whole sheet, but which Friends are available to add is Class-dependent, so if the character doesn't have a Class yet, there won't be any Friends to show up in the dialog box.  Once you add the Class, the Friends list should properly populate.  Let me know if that's not the case, but I'm not seeing any issues with that in my testing.

**Comment by brunocalado** [comment]
Worked now. Tks
