### ISSUE TITLE
Add GATHER INFORMATION to Fortune

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#50]
Hi.

Can you add GATHER INFORMATION text to the fortune roll?
![image](https://user-images.githubusercontent.com/4999783/150639076-975d5017-3e85-45ff-8894-63c3c081deb1.png)

![image](https://user-images.githubusercontent.com/4999783/150639096-f312bc11-b052-4c88-942f-f7de06d6aa69.png)

tks

**Comment by drewg13** [comment]
I feel like this is covered adequately by "You get a good result or full effect."  There are lots of things you could use a Fortune Roll for and adding details for all of them would just make the chat results bloated.  Also, Gather Information is not necessarily a Fortune Roll either.

**Comment by brunocalado** [comment]
Hi.

I did this in the translation. It did not fell bloated. 
![image](https://user-images.githubusercontent.com/4999783/150704352-118ea954-dd61-4c38-9c1b-f43883d5f140.png)

About gather, I asked about the sav rule. This guy provided a cool awnser.
https://discord.com/channels/325094888133885952/475808865502625807/934923740658159626
I basically translated:
```
- 1-3? Not much at all. But they should get something!!! Even if that means “Oh, you know Slithers has the information, but no way can you wirelessly hack it… you need physical access.” (And that’s probably gonna be an Action Roll)
- 4/5: Not bad, but not great either. “Slithers knows where the deal is going down… but he doesn’t know who the buyer is.”
- 6: Pretty darn good information: “Slithers knows where the deal is, knows the Wolves are buying for some sort of big mission.”
- Crit: A whole heck of a lot: “Slithers knows the place. Wolves are involved. They’re gearing up to betray the people who contracted them.”
```
