### ISSUE TITLE
Improve Faction Sheet

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#54]
Hi!

Can you improve the Faction UI? 

![image](https://user-images.githubusercontent.com/4999783/151701837-b0ab9a2f-2385-4ac7-9835-21c5d3b75c47.png)

Suggestions:

- [ ] Make the fields: faction type and tier smaller. Also, put them next to each other.
- [ ] Move the goal to text next to each other
- [ ] Move Turf and Assets next to each other
- [ ] Move allies and enemies next to each other
Example:
![image](https://user-images.githubusercontent.com/4999783/151702055-1c5f0d29-f95e-4ba3-97bb-d262865bff83.png)

**Comment by drewg13** [comment]
It's a lot easier to do with cut-and-paste than in HTML.  For me, at least.  I'll see what I can do, but making things look nice is not my greatest skill.

**Comment by brunocalado** [comment]
> It's a lot easier to do with cut-and-paste than in HTML. For me, at least. I'll see what I can do, but making things look nice is not my greatest skill.

There is a simple solution. Replace most fields with a single field which is basically a formatted journal.

**Comment by drewg13** [comment]
v 1.15.3
