### ISSUE TITLE
Fortune Roll Actor Sheet Shortcut

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#55]
Hi.

The fortune roll is used a lot.

Is it possible to add a shortcut to it in the player actor sheet?

Perhaps, put the shortcut either above or below the actions.
![image](https://user-images.githubusercontent.com/4999783/151702433-36009ddd-8779-45b0-9b33-8f3bff265ffc.png)

**Comment by drewg13** [comment]
I don't see how adding it to the actor sheet could possibly be more convenient than having it always present in the toolbar.  Everyone has access to it at all times, why would you need it elsewhere?

**Comment by brunocalado** [comment]
> I don't see how adding it to the actor sheet could possibly be more convenient than having it always present in the toolbar. Everyone has access to it at all times, why would you need it elsewhere?

- Some modules hide the tool bar (minimal ui)
- NEVER underestimate an user. Last session they took their time to find the button
- It's convenient to have all the functions in one place. In this case, on the character sheet.

**Comment by drewg13** [comment]
Yeah, I see your point, but I don't design UI with mods in mind and users having some trouble finding it is a one-time issue.  Personally, I do the large majority of Fortune/Engagement rolls myself as GM, I've never had a player roll one, so the current setup still makes more sense to me with the PC sheets already fairly crowded with information.

**Comment by brunocalado** [comment]
I ask them a lot of fortune rolls. I'll read the rules better then
