### ISSUE TITLE
[BUG] Fail to Duplicate Actor

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#58]
Hi!

When I duplicate an actor it looses the image on it.

https://user-images.githubusercontent.com/4999783/154473505-0304ee97-263b-4932-9d52-b72cfa012f1d.mp4

**Comment by drewg13** [comment]
I see what happened there, when it goes through the Actor creation workflow, I override the img attribute without considering whether there's already something there.  Easy fix.

**Comment by drewg13** [comment]
Fixed in 1.15.4
