### ISSUE TITLE
[Bug] Special Chars

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#60]
Hi.

My language has special chars. They use html code on the actor sheet. Can you fix it?
![image](https://user-images.githubusercontent.com/4999783/155318519-3f49b4d0-a87b-4d52-b930-685e1bfa7f6b.png)

tks

**Comment by drewg13** [comment]
I have a pretty good idea what the fix is, but can you attach an exported JSON of an affected item so I can test?
