### ISSUE TITLE
More Options for the "Change XP Bars" Macro

### ISSUE THREAD

**Issue by Medugenus** [drewg13/foundryvtt-scum-and-villainy#66]
More of a feature request, but I am new to github and did not know where to post.

It would be awesome if the mentioned Macro could change all the bars, I was trying to implement a homebrew ship and as is it has 4 bars in every system i would like to change weapon to 2 bars for instance.

If there is a easier way pls let me know.

**Comment by Medugenus** [comment]
![image](https://user-images.githubusercontent.com/66615111/205077758-6c393d47-5ffe-40e9-b786-8e0d3a8e152e.png)

**Comment by the-bowmanizer** [comment]
You can change this in the ship under the effects tab, then edit the passive effect for the ship type.

![image](https://user-images.githubusercontent.com/105297243/205080602-3c392316-d314-4637-b680-da9526e46d91.png)

**Comment by Medugenus** [comment]
Perfect works fine.  Thx for the help
