### ISSUE TITLE
Trauma tooptip is showing under the trauma.

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#7]
Trauma tooptip is showing under the trauma.
![image](https://user-images.githubusercontent.com/4999783/132139135-d715b8ae-580d-4aff-bb53-014ef7ea7056.png)

Thank you for the great work.

**Comment by drewg13** [comment]
I'm aware of this one and haven't figured out how to fix it.  I'm not even sure why it behaves differently from the others.  I'm really terrible at CSS, I'm afraid.  I tried a few more ideas today, but no improvement.  I'll continue to think about it.

**Comment by brunocalado** [comment]
I wish I could help. But, the discord dev channel can. You could ask them.
![image](https://user-images.githubusercontent.com/4999783/132259644-fe2d0002-7c9e-48f0-90ea-6f7b9ff70b5f.png)

There is also the league for support.

![image](https://user-images.githubusercontent.com/4999783/132259626-ed1c72ee-6d03-42df-b5fe-3dc04bc3fa14.png)

**Comment by drewg13** [comment]
Thanks, I know the discord options, I usually prefer to work things out for myself if I can.  It will likely require a rewrite/restructure to fix it.

**Comment by drewg13** [comment]
Figured it out, I knew it would be something relatively simple.  Fixed in 1.9.4.
