### ISSUE TITLE
Can't translate current load

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#8]
Hi. Can you add a localization tag for current load? Thank you.

![image](https://user-images.githubusercontent.com/4999783/132139713-59ee4fe4-f696-4168-bda7-64b69ea9cb77.png)

**Comment by drewg13** [comment]
Yep, missed that localization.  I'll make a release momentarily to fix it.  If you'd like to share your translation, I'd be happy to include it.

**Comment by brunocalado** [comment]
Thank you. I added "BITD.CurrLoad": "Carga Atual already.

The translation is in this module: https://github.com/brunocalado/scum-and-villainy-pt-br

**Comment by drewg13** [comment]
Done!  Thanks!

**Comment by brunocalado** [comment]
Oh no... Sorry. I'm not finish with the translation yet. 

That's why I'm pushing to the module. So I can push it without annoy you.

I just send the link because I was unsure if "BITD.CurrLoad": was correct.
