### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by lwd-hollis** [drewg13/foundryvtt-scum-and-villainy#80]
I'm getting an error when trying to update.

Warning: SETUP.PackageUpdateCoreundefined

![image](https://github.com/drewg13/foundryvtt-scum-and-villainy/assets/44179961/b1502390-c440-4b2c-84f4-cd1a3060e2f9)

**Comment by drewg13** [comment]
I'll look into it.  There's some core Foundry conflict between V11 and the V12-only update I just released.  You're not missing anything new, just compatibility updates that have no relevance to V11.

**Comment by drewg13** [comment]
It's a bug in Foundry V11 and how it handles an update that requires a new core version that's not stable yet.  I can't do anything about this, sorry.
