### ISSUE TITLE
Renaming Faction Status Actors

### ISSUE THREAD

**Issue by H-O-W-L-45** [drewg13/foundryvtt-scum-and-villainy#81]
Currently in 2.2.4 there is no way to rename Faction Status actors. A field to rename these would be nice, as populating them with Faction Status information is a relatively (I say relatively; it's still easy) time-intensive procedure for a system that's otherwise very lightweight. Having to recreate the whole actor for a typo or a naming order issue is a bit tedious.

**Comment by drewg13** [comment]
Interesting, how many Faction Status Actors are you using?  I generally just use one per campaign.  I could also give you a macro script to change it as a stopgap.

**Comment by H-O-W-L-45** [comment]
I'm using one per character, since I'm running a rotating one-on-one with drop-ins kind of campaign as I wanted more character agency with factions, which S&V actually works surprisingly well for. A macro would be great, thanks.

**Comment by drewg13** [comment]
OK, while I think on this and work on V12 stuff, here's a macro method for you.
First, open your Faction Status Actor and right-click here:
![image](https://github.com/drewg13/foundryvtt-scum-and-villainy/assets/1455026/0cc02bde-e2c9-4c39-aa3b-c18f6fbf646f)
That will copy the Actor's UUID to your clipboard.  If it doesn't start with Actor. then you used the wrong click.
Then open a new script macro and copy this into it.
```js
let actor = await fromUuid("actor-uuid-here");
await actor.update({name: "your-new-name-here"});
```
Then replace the relevant sections with your desired info, making sure you maintain the quote, and Execute.  It should be immediate.
Save and repeat for each Actor by changing out the UUID and new name, as needed.

**Comment by drewg13** [comment]
I added a setting for this.
