### ISSUE TITLE
Duplicate Translation Tag?

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#9]
Hi.

You have
- "BITD.vice"
- "BITD.Vice"

I think it's duplicated.

Tks.

https://github.com/drewg13/foundryvtt-scum-and-villainy/blob/master/lang/en.json

**Comment by drewg13** [comment]
No, the lower case items are for localizing the title bars of various dialogs.  They're different, that's why all the lower case ones are grouped together.
